#!/bin/bash
echo "=== FILES CREATED DURING DEPLOYMENT ==="
echo ""
echo "1. Directories created with mkdir -p:"
echo "   - /opt/live-sales-platform (APP_DIR)"
echo "   - uploads/"
echo "   - backups/"
echo "   - nginx/ssl/"
echo "   - nginx/conf.d/"
echo "   - frontend/ (already exists from git clone)"
echo "   - backend/ (already exists from git clone)"
echo ""
echo "2. Configuration files created:"
echo "   - .env (backend environment variables)"
echo "   - frontend/.env.production (frontend API URL)"
echo "   - nginx/nginx.conf (Nginx configuration)"
echo "   - docker-compose.prod.yml (production Docker Compose)"
echo "   - backup.sh (backup script)"
echo ""
echo "3. SSL certificate symlinks (if domain configured):"
echo "   - nginx/ssl/fullchain.pem -> /etc/letsencrypt/live/\$DOMAIN/fullchain.pem"
echo "   - nginx/ssl/privkey.pem -> /etc/letsencrypt/live/\$DOMAIN/privkey.pem"
echo ""
echo "4. Backup files (created by backup.sh, not during initial deploy):"
echo "   - backups/lspd_\$DATE.db"
echo "   - backups/uploads_\$DATE.tar.gz"
echo "   - backups/env_\$DATE.backup"
echo "   - backups/backup_\$DATE.log"
echo ""
echo "=== ANALYSIS ==="
echo ""
echo "NECESSARY FILES (required for application to run):"
echo "1. .env - Contains JWT_SECRET and database configuration (REQUIRED)"
echo "2. frontend/.env.production - Contains API URL for frontend (REQUIRED)"
echo "3. nginx/nginx.conf - Nginx reverse proxy configuration (REQUIRED)"
echo "4. docker-compose.prod.yml - Docker Compose for production (REQUIRED)"
echo "5. SSL certificates/symlinks - For HTTPS (OPTIONAL, only if using domain)"
echo ""
echo "POTENTIALLY UNNECESSARY FILES:"
echo "1. backup.sh - Could be optional if user doesn't want backups"
echo "2. Creating frontend/ and backend/ directories - Already exist from git clone"
echo "3. Multiple nginx configs - Script creates both HTTP and HTTPS versions"
echo ""
echo "DIRECTORIES THAT MIGHT BE UNNECESSARY:"
echo "1. nginx/conf.d/ - Not used in current nginx.conf"
echo "2. Creating frontend/ and backend/ - Redundant since git clone creates them"
